Add fileExists mock
jenkinsci/JenkinsPipelineUnit pull request #306
Opened 2020-10-06 16:55 UTC by cwiggs

This commit adds the fileExist mock that returns "true".  Adding it here so people don't have to mock such a simple step when using the JenkinsPipelineUnit framework.

2020-10-06 19:02 UTC, nre-ableton commented
I don't think we should add a mock for this. Returning `true` in all cases makes a pretty broad assumption that isn't always true for pipelines in many cases. Leaving this step unmocked means that users must add their own mock for it, which I think is good to pass the responsibility to them.

If we were to add a mock for `fileExists` to this library, I'd prefer it to be similar to the `readFile` mock, meaning that there would be a [separate helper method](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L571) to register the output that should be returned for a given filename.

2020-10-16 11:17 UTC, stchar approved these changes

2020-10-16 11:21 UTC, stchar requested changes
@nre-ableton is right additional logic is required to filter what files should exist in which tests.

2020-10-16 14:01 UTC, nre-ableton commented
See https://github.com/jenkinsci/JenkinsPipelineUnit/pull/312.

2020-10-20 18:34 UTC, cwiggs commented
#312 Looks good to me, thanks!  You can close this PR.

2020-10-20 18:35 UTC, closed without merging